# Generated by Django 4.2.7 on 2026-03-03 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_customuser_approval_status_booking_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text='Name of the business.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the business.')),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email for the business.', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number.', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Business address.')),
                ('logo_url', models.URLField(blank=True, help_text='URL to business logo.')),
                ('website', models.URLField(blank=True, help_text='Business website URL.')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether the vendor is approved to display products.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_vendor',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a vendor.'),
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product or service name.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the product/service.')),
                ('category', models.CharField(choices=[('transportation', 'Transportation'), ('accommodation', 'Accommodation'), ('tourism', 'Tourism'), ('food', 'Food & Dining'), ('equipment', 'Travel Equipment'), ('insurance', 'Travel Insurance'), ('other', 'Other')], default='other', help_text='Product category.', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the product/service.', max_digits=10, null=True)),
                ('price_unit', models.CharField(blank=True, help_text='Unit for price (e.g., per night, per person).', max_length=50)),
                ('image_url', models.URLField(blank=True, help_text='URL to product image.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the product is active and visible.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(help_text='Vendor who owns this product.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='booking.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(help_text='User who owns this vendor profile.', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
